server:
  port: 8222

# main:
#   allow-bean-definition-overriding: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            # allowCredentials: true

      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**


eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
