server:
  port: 8222

main:
  allow-bean-definition-overriding: true

spring:
  cloud:
    gateway:
      # discovery:
      #   locator:
      #     enabled: true
      #     lower-case-service-id: true
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "http://localhost:5173"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

    routes:
      - id: PRODUCT-SERVICE
        # uri: lb:http://PRODUCT-SERVICE
        uri: lb://product-service
        predicates:
          - Path=/api/v1/products/**
