server:
  port: 8222

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://localhost:8181
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: product-service
          uri: lb://product-service
          filters:
            - DedupeResponseHeader=Vary
          predicates:
            - Path=/api/v1/products/**

        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/api/v1/carts/**

        - id: auth-service
          uri: lb://auth-service
          filters:
            - DedupeResponseHeader=Vary
          predicates:
            - Path=/api/v1/auth/**



logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
