server:
  port: 8222

jwt:
  auth:
    converter:
      resource-id: tech_shop_auth
      principal-attribute: preferred_username

main:
  allow-bean-definition-overriding: true

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/realms/tech_shop_auth_api
          jwt-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  cloud:
    discovery:
      locator:
        enabled: true

    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "http://localhost:5173"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

    routes:
      - id: product-service
        uri: lb:http://PRODUCT-SERVICE
        predicates:
          - Path=/api/v1/products/**
          - Path=/api/v1/categories/**
