server:
  port: 8222

main:
  allow-bean-definition-overriding: true

spring:
  cloud:
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true

    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "http://localhost:5173"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

    routes:
      - id: product-service
        # uri: lb:http://PRODUCT-SERVICE
        uri: lb://PRODUCT-SERVICE
        predicates:
          - Path=/api/v1/products/**
