spring:
  application:
    name: product-service

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8081

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gearvn?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    # show-sql: true

cors:
  allowed-origins: http://localhost:5173

hibernate:
  search:
    default:
      directory_provider: filesystem
      indexBase: ./src/main/resources/static

  # main:
  #   allow-bean-definition-overriding: true

  # security:
  #   oauth2:
  #     resourceserver:
  #       jwt:
  #         issuer-uri: http://localhost:8088/realms/tech_shop_auth_api
  #         jwt-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  # keycloak:
  #   auth-server-url: http://localhost:8088/realms/tech_shop_auth_api
  #   realm: tech_shop_auth_api
  #   bearer-only: true
  #   resource: tech_shop_auth
# jwt:
#   auth:
#     converter:
#       resource-id: tech_shop_auth
#       principal-attribute: preferred_username

