# server.port=8082
#
# spring.datasource.url=jdbc:mysql://localhost:3306/product_db
# spring.datasource.usename=root
# spring.datasource.password=root
# spring.jpa.hibernate.ddl-auto=update


server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_db
    username: root
    password: root

